use_frameworks!

platform :ios, '10.0'

target 'IJKMediaFramework_Example' do
  pod 'IJKMediaFramework', :path => '../'

  target 'IJKMediaFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
