use_frameworks!

platform :ios, '12.0'

target 'IJKMediaFramework_Example' do
  pod 'IJKMediaFramework', :path => '../'

  target 'IJKMediaFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
end